# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy yamiweb

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Update this to the desired Node.js version

    - name: Install dependencies
      run: ls /home && npm --location=global i yarn

    - name: Build NextJS
      run: |
        yarn
        yarn build
        pwd

    - name: Update Project On VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Workspace Path: $GITHUB_WORKSPACE"
          [ "haniv" = ${{ secrets.USERNAME }} ] && echo "The strings are equal." || echo "The strings are not equal."
          #cd /home/haniv/apps/yamiweb
          #git pull origin dev
          #yarn
          #cp -R node_modules .next /home/haniv/apps/yamiweb
